name: PR Validation

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  validate:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.X
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run TypeScript Compiler
        run: npm run tsc

      - name: Run Tests
        run: npm run test

      - name: Build WebAssembly Plugin
        run: npm run build
